### ISSUE TITLE
SfM library used in your work

### ISSUE THREAD

**Issue by salykovaa** [zju3dv/AutoRecon#1]
Hi,

thanks for your great project! I've just finished to read the paper. May I know what software/library did you use for SfM? I see you add a few modifications to the standard SfM pipeline (e.g. LoFTR matcher instead sparse key points). just curious what open-source SfM library is easy to extend and best suitable for this task

**Comment by pengsida** [comment]
Hi,

A similar approach is described in this paper: https://github.com/zju3dv/DetectorFreeSfM

Best,
Sida

**Comment by pablovela5620** [comment]
is the plan that DetectorFreeSfM will be released concurrently with AutoRecon? Thanks for the great work, excited to try it out
