### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by Haobo-Liu** [zju3dv/AutoRecon#11]
[Errno 2] No such file or directory: 'data/CO3D_DEMO/scan1/triangulate_loftr-720000_sequential_np-10/auto-deocomp_sfm-tra                       nsformer_cvpr/cameras_cameras_norm-obj-side-2.0.npz'

Could you please tell me how to fix it?

**Comment by Zeng-Fan-Yi** [comment]
I have encountered a problem similar to yours, have you solved it?

**Comment by Haobo-Liu** [comment]
not yet



---Original---
From: ***@***.***&gt;
Date: Mon, Jan 29, 2024 19:27 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;"State ***@***.***&gt;;
Subject: Re: [zju3dv/AutoRecon] FileNotFoundError (Issue #11)




 
I have encountered a problem similar to yours, have you solved it?
