### ISSUE TITLE
Code release timeline

### ISSUE THREAD

**Issue by pratham15** [zju3dv/AutoRecon#2]
Having read the paper and realising how out-of-the-box the ordeal for your approach is, I'm really excited and curious for the release.

When are you planning the code-release?

**Comment by pengsida** [comment]
Hi,

Thank you for your interest.
We will release the code very recently. Specifically, it is expected to be released within one week.

Best,
Sida

**Comment by RasenRhino** [comment]
Hi @pengsida , 
eagerly waiting for the code release. 
Any updates for the same?
Thank you

**Comment by pengsida** [comment]
Hi @RasenRhino,

We have released the code.

Thank you!
